using PianoMan.Core.Analysis;using PianoMan.Core.Chess;using PianoMan.Core.Theory;
namespace PianoMan.Tests;
public sealed class TheoryBookTests
{
    [Fact] public void ExpectedV1CorpusMetadataIsPinned(){Assert.Equal(251_274,TheoryBookExpectedMetadata.UniquePositions);Assert.Equal(420_150,TheoryBookExpectedMetadata.Continuations);Assert.Equal(3_329,TheoryBookExpectedMetadata.OpeningIdentities);Assert.Equal(36,TheoryBookExpectedMetadata.MaxPlies);Assert.Equal(7_586_743,TheoryBookExpectedMetadata.RawBytes);Assert.Equal(2_910_309,TheoryBookExpectedMetadata.CompressedBytes);Assert.Equal("36cd056f0fdea527c25fa40b184ae26ef0f5eafb9722a796be9cae0d36927d47",TheoryBookExpectedMetadata.CompressedSha256);}
    [Fact] public void EmbeddedBrotliResourceMatchesPinnedV1Metadata(){var book=TheoryBook.LoadEmbedded();Assert.NotNull(book);Assert.Equal("1",book.Metadata.Version);Assert.Equal(TheoryBookExpectedMetadata.UniquePositions,book.Metadata.UniquePositions);Assert.Equal(TheoryBookExpectedMetadata.Continuations,book.Metadata.Continuations);Assert.Equal(TheoryBookExpectedMetadata.OpeningIdentities,book.Metadata.OpeningIdentities);Assert.Equal(TheoryBookExpectedMetadata.MaxPlies,book.Metadata.MaxPlies);Assert.Equal(TheoryBookExpectedMetadata.RawBytes,book.Metadata.RawBytes);Assert.Equal(TheoryBookExpectedMetadata.CompressedBytes,book.Metadata.CompressedBytes);Assert.Equal(TheoryBookExpectedMetadata.CompressedSha256,book.Metadata.CompressedSha256);Assert.Equal(TheoryBookExpectedMetadata.StockfishCommit,book.Metadata.StockfishCommit);Assert.Equal(TheoryBookExpectedMetadata.LichessCommit,book.Metadata.LichessCommit);Assert.Equal(TheoryBookExpectedMetadata.StockfishZipSha256,book.Metadata.StockfishZipSha256);Assert.Equal(TheoryBookExpectedMetadata.StockfishPgnSha256,book.Metadata.StockfishPgnSha256);}
    [Fact] public void InitialPositionContainsE4AndD4(){var book=TheoryBook.LoadEmbedded();var lookup=book.Lookup(Position.Initial);Assert.NotNull(lookup);var ucis=lookup!.Continuations.Select(c=>PackedMove.Resolve(Position.Initial,c.PackedMove).ToUci()).ToArray();Assert.Contains("e2e4",ucis);Assert.Contains("d2d4",ucis);}
    [Fact] public void KnownMoveIsMarkedTheory(){var p=Position.Initial;var move=SanParser.Parse(p,"e4");var result=GameAnalyzer.AnalyzeMove(p,move,TheoryBook.LoadEmbedded());Assert.Equal(AnalysisMode.Theory,result.Mode);Assert.Equal("TEORÍA · SIN BÚSQUEDA",result.Label);Assert.Null(result.Loss);}
    [Fact] public void PositionOutsideBookEvaluatesEveryLegalMove(){var p=Fen.Parse("4k3/8/8/8/8/8/4P3/4K3 w - - 0 1");var played=SanParser.Parse(p,"e4");var legal=MoveGenerator.GenerateLegalMoves(p).Count;var result=GameAnalyzer.AnalyzeMove(p,played,TheoryBook.LoadEmbedded());Assert.Equal(AnalysisMode.Tuning,result.Mode);Assert.Equal(legal,result.EvaluatedMoveCount);Assert.InRange(result.Candidates.Count,1,11);}
}
