using PianoMan.Core.Chess;
namespace PianoMan.Core.Harmony;
public sealed class HarmonyAnalyzer
{
    public static HarmonySnapshot Analyze(Position p)
    {
        ArgumentNullException.ThrowIfNull(p);var w=AnalyzeSide(p,Color.White);var b=AnalyzeSide(p,Color.Black);var legal=MoveGenerator.GenerateLegalMoves(p);var check=MoveGenerator.IsKingInCheck(p,p.SideToMove);var status=legal.Count>0?PositionStatus.Ongoing:check?PositionStatus.Checkmate:PositionStatus.Stalemate;var winner=status==PositionStatus.Checkmate?p.SideToMove.Opposite():(Color?)null;var score=status switch{PositionStatus.Checkmate when winner==Color.White=>100_000,PositionStatus.Checkmate=>-100_000,PositionStatus.Stalemate=>0,_=>w.Total-b.Total};var tension=status==PositionStatus.Ongoing?CalculateTension(p):0;return new HarmonySnapshot(w,b,score,tension,CalculatePhase(p),p.SideToMove,status,winner);
    }
    private static SideHarmony AnalyzeSide(Position p,Color color)
    {
        var material=0;var defended=0;foreach(var(s,piece)in p.Pieces()){if(piece.Color!=color)continue;material+=PieceValue(piece.Type);if(piece.Type!=PieceType.King&&MoveGenerator.IsSquareAttacked(p,s,color))defended++;}var attacked=MoveGenerator.CountAttackedSquares(p,color);return new SideHarmony(material,attacked*2,defended*4,EvaluateKingSafety(p,color),CountSpace(p,color),EvaluatePawnStructure(p,color),EvaluatePressure(p,color),p.SideToMove==color?8:0);
    }
    private static int CountSpace(Position p,Color color){var count=0;var first=color==Color.White?4:0;var last=color==Color.White?7:3;for(var r=first;r<=last;r++)for(var f=0;f<8;f++)if(MoveGenerator.IsSquareAttacked(p,Square.FromCoordinates(f,r),color))count+=2;return count;}
    private static int EvaluatePawnStructure(Position p,Color color)
    {
        var files=Enumerable.Range(0,8).Select(_=>new List<int>()).ToArray();foreach(var(s,piece)in p.Pieces())if(piece==new Piece(color,PieceType.Pawn))files[Square.File(s)].Add(Square.Rank(s));var score=0;for(var f=0;f<8;f++){var ranks=files[f];if(ranks.Count>1)score-=(ranks.Count-1)*12;foreach(var rank in ranks){if(!HasPawn(files,f-1)&&!HasPawn(files,f+1))score-=8;if(Connected(files,f,rank))score+=4;if(IsPassed(p,color,f,rank)){var advance=color==Color.White?rank-1:6-rank;score+=5+Math.Max(0,advance)*3;}}}return score;
    }
    private static bool HasPawn(List<int>[] files,int file)=>file is >=0 and <8&&files[file].Count>0;
    private static bool Connected(List<int>[] files,int file,int rank){foreach(var af in new[]{file-1,file+1})if(af is >=0 and <8&&files[af].Any(r=>Math.Abs(r-rank)<=1))return true;return false;}
    private static bool IsPassed(Position p,Color color,int file,int rank){var enemy=new Piece(color.Opposite(),PieceType.Pawn);var d=color==Color.White?1:-1;for(var r=rank+d;r is >=0 and <8;r+=d)for(var f=Math.Max(0,file-1);f<=Math.Min(7,file+1);f++)if(p[Square.FromCoordinates(f,r)]==enemy)return false;return true;}
    private static int EvaluateKingSafety(Position p,Color color){var king=p.FindKing(color);if(king<0)return-500;var score=0;var kf=Square.File(king);var kr=Square.Rank(king);var shield=kr+(color==Color.White?1:-1);if(shield is >=0 and <8)for(var f=Math.Max(0,kf-1);f<=Math.Min(7,kf+1);f++)if(p[Square.FromCoordinates(f,shield)]==new Piece(color,PieceType.Pawn))score+=10;foreach(var s in KingZone(king))if(MoveGenerator.IsSquareAttacked(p,s,color.Opposite()))score-=12;if(MoveGenerator.IsKingInCheck(p,color))score-=50;var home=color==Color.White?0:7;if(kr==home&&kf is 2 or 6)score+=12;if(!p.Pieces().Any(e=>e.Piece==new Piece(color,PieceType.Pawn)&&Square.File(e.Square)==kf))score-=8;return score;}
    private static int EvaluatePressure(Position p,Color color){var opp=color.Opposite();var score=0;foreach(var(s,piece)in p.Pieces()){if(piece.Color!=opp||!MoveGenerator.IsSquareAttacked(p,s,color))continue;score+=piece.Type switch{PieceType.Pawn=>3,PieceType.Knight or PieceType.Bishop=>8,PieceType.Rook=>12,PieceType.Queen=>18,PieceType.King=>20,_=>0};if(piece.Type!=PieceType.King&&!MoveGenerator.IsSquareAttacked(p,s,opp))score+=10;}var king=p.FindKing(opp);if(king>=0)score+=KingZone(king).Count(s=>MoveGenerator.IsSquareAttacked(p,s,color))*5;return score;}
    private static int CalculateTension(Position p){var t=0;if(MoveGenerator.IsKingInCheck(p,Color.White))t+=70;if(MoveGenerator.IsKingInCheck(p,Color.Black))t+=70;foreach(var(s,piece)in p.Pieces()){if(piece.Type==PieceType.King)continue;var opp=piece.Color.Opposite();if(!MoveGenerator.IsSquareAttacked(p,s,opp))continue;var local=Math.Max(2,PieceValue(piece.Type)/40);if(!MoveGenerator.IsSquareAttacked(p,s,piece.Color))local*=2;t+=local;}foreach(var c in new[]{Color.White,Color.Black})t+=MoveGenerator.GenerateLegalMoves(p.WithSideToMove(c)).Count(m=>m.IsCapture)*2;return Math.Min(255,t);}
    private static int CalculatePhase(Position p){var rem=p.Pieces().Sum(e=>e.Piece.Type switch{PieceType.Knight or PieceType.Bishop=>1,PieceType.Rook=>2,PieceType.Queen=>4,_=>0});return Math.Clamp(rem*100/24,0,100);}
    private static IEnumerable<int> KingZone(int king){var kf=Square.File(king);var kr=Square.Rank(king);for(var f=kf-1;f<=kf+1;f++)for(var r=kr-1;r<=kr+1;r++)if(Square.IsValid(f,r))yield return Square.FromCoordinates(f,r);}
    public static int PieceValue(PieceType t)=>t switch{PieceType.Pawn=>100,PieceType.Knight=>320,PieceType.Bishop=>330,PieceType.Rook=>500,PieceType.Queen=>900,_=>0};
}
