<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PianoMan.Core</RootNamespace>
    <AssemblyName>PianoMan.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/theory-book-v1.bin.br" LogicalName="PianoMan.Core.Resources.theory-book-v1.bin.br" />
    <EmbeddedResource Include="Resources/theory-book-v1.manifest.json" LogicalName="PianoMan.Core.Resources.theory-book-v1.manifest.json" />
  </ItemGroup>
</Project>
